### ISSUE TITLE
error while scanning

### ISSUE THREAD

**Issue by mhdashikofficial** [shinyxn/chitanda-bot#1]
at Receiver.emit (node:events:518:28) {
  data: { tag: 'stream:error', attrs: { code: '515' }, content: undefined },
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 515,
    payload: {
      statusCode: 515,
      error: 'Unknown',
      message: 'Stream Errored (restart required)'
    },
    headers: {}
  }
} , reconnecting  true

**Comment by shinyxn** [comment]
Hello, thank you for informing me about this issue. I apologize for the delayed response. I haven't worked on this project for quite some time. 

Regarding the problem you're experiencing, try running the `index.js` file again quickly after the error occurs. I think it's because the recursive function that calls the init function isn't being triggered due to the `shouldReconnect` condition not being met or being broken. I will try to fix it when I have time

**Comment by shinyxn** [comment]
fixed https://github.com/shinyxn/chitanda-bot/commit/4fc6f61a12fc34b766d39d3cda527c8f15573f66
